server {
    listen 80;
    listen [::]:80;
    server_name upbid.store;
    return 301 https://www.upbid.store$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name upbid.store;

    ssl_certificate     /etc/letsencrypt/live/upbid.store/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/upbid.store/privkey.pem;

    return 301 https://www.upbid.store$request_uri;
}
